version: '3'
services:
  go-microservice:
    build: .
    image: clean-architecture-gorm-mysql
    environment:
      - MYSQL_URL=sql://user:pass
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mysqldb
    #volumes:
    #  - .:/srv/go-app
    networks:
      - go-network
  mysqldb:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'todolist_go'
      MYSQL_ROOT_PASSWORD: 'youShouldChangeThisPassword'
      MYSQL_HOST: "%"
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'youShouldChangeThisPassword'
    ports:
      - '33006:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/scripts/schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    networks:
      - go-network

volumes:
  dbdata:

networks:
  go-network:
    driver: bridge
